steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
  - '-c'
  - >-
    docker
    build
    --target 
    base-builder
    --tag
    gcr.io/$PROJECT_ID/$_APP_NAME-builder:$SHORT_SHA
    --tag
    gcr.io/$PROJECT_ID/$_APP_NAME-builder:latest .
images:
- 'gcr.io/$PROJECT_ID/$_APP_NAME-builder:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/$_APP_NAME-builder:latest'
